// Code generated by protoc-gen-go.
// source: bot.proto
// DO NOT EDIT!

/*
Package bot is a generated protocol buffer package.

It is generated from these files:
	bot.proto

It has these top-level messages:
	RetrieveActivitiesRequest
	SendDirectRequest
	RetrieveActivitiesReply
	SendDirectReply
	Activity
	SaveProductResult
	NotifyMessageRequest
	NotifyMessageResult
*/
package bot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RetrieveActivitiesRequest struct {
	MentionName string `protobuf:"bytes,1,opt,name=mention_name,json=mentionName" json:"mention_name,omitempty"`
	AfterId     int64  `protobuf:"varint,2,opt,name=after_id,json=afterId" json:"after_id,omitempty"`
	Type        string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Limit       int64  `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
}

func (m *RetrieveActivitiesRequest) Reset()                    { *m = RetrieveActivitiesRequest{} }
func (m *RetrieveActivitiesRequest) String() string            { return proto.CompactTextString(m) }
func (*RetrieveActivitiesRequest) ProtoMessage()               {}
func (*RetrieveActivitiesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SendDirectRequest struct {
	ThreadId string `protobuf:"bytes,1,opt,name=thread_id,json=threadId" json:"thread_id,omitempty"`
	Text     string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *SendDirectRequest) Reset()                    { *m = SendDirectRequest{} }
func (m *SendDirectRequest) String() string            { return proto.CompactTextString(m) }
func (*SendDirectRequest) ProtoMessage()               {}
func (*SendDirectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RetrieveActivitiesReply struct {
	Result []*Activity `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *RetrieveActivitiesReply) Reset()                    { *m = RetrieveActivitiesReply{} }
func (m *RetrieveActivitiesReply) String() string            { return proto.CompactTextString(m) }
func (*RetrieveActivitiesReply) ProtoMessage()               {}
func (*RetrieveActivitiesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RetrieveActivitiesReply) GetResult() []*Activity {
	if m != nil {
		return m.Result
	}
	return nil
}

type SendDirectReply struct {
}

func (m *SendDirectReply) Reset()                    { *m = SendDirectReply{} }
func (m *SendDirectReply) String() string            { return proto.CompactTextString(m) }
func (*SendDirectReply) ProtoMessage()               {}
func (*SendDirectReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Activity struct {
	Id                int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pk                string `protobuf:"bytes,2,opt,name=pk" json:"pk,omitempty"`
	MediaId           string `protobuf:"bytes,3,opt,name=media_id,json=mediaId" json:"media_id,omitempty"`
	MediaUrl          string `protobuf:"bytes,4,opt,name=media_url,json=mediaUrl" json:"media_url,omitempty"`
	UserId            int64  `protobuf:"varint,5,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName          string `protobuf:"bytes,6,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	UserImageUrl      string `protobuf:"bytes,7,opt,name=user_image_url,json=userImageUrl" json:"user_image_url,omitempty"`
	MentionedUsername string `protobuf:"bytes,8,opt,name=mentioned_username,json=mentionedUsername" json:"mentioned_username,omitempty"`
	Type              string `protobuf:"bytes,9,opt,name=type" json:"type,omitempty"`
	Comment           string `protobuf:"bytes,10,opt,name=comment" json:"comment,omitempty"`
	CreatedAt         int64  `protobuf:"varint,11,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	DirectThreadId    string `protobuf:"bytes,12,opt,name=direct_thread_id,json=directThreadId" json:"direct_thread_id,omitempty"`
}

func (m *Activity) Reset()                    { *m = Activity{} }
func (m *Activity) String() string            { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()               {}
func (*Activity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SaveProductResult struct {
	Id    int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Retry bool  `protobuf:"varint,2,opt,name=retry" json:"retry,omitempty"`
}

func (m *SaveProductResult) Reset()                    { *m = SaveProductResult{} }
func (m *SaveProductResult) String() string            { return proto.CompactTextString(m) }
func (*SaveProductResult) ProtoMessage()               {}
func (*SaveProductResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type NotifyMessageRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *NotifyMessageRequest) Reset()                    { *m = NotifyMessageRequest{} }
func (m *NotifyMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*NotifyMessageRequest) ProtoMessage()               {}
func (*NotifyMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type NotifyMessageResult struct {
}

func (m *NotifyMessageResult) Reset()                    { *m = NotifyMessageResult{} }
func (m *NotifyMessageResult) String() string            { return proto.CompactTextString(m) }
func (*NotifyMessageResult) ProtoMessage()               {}
func (*NotifyMessageResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*RetrieveActivitiesRequest)(nil), "bot.RetrieveActivitiesRequest")
	proto.RegisterType((*SendDirectRequest)(nil), "bot.SendDirectRequest")
	proto.RegisterType((*RetrieveActivitiesReply)(nil), "bot.RetrieveActivitiesReply")
	proto.RegisterType((*SendDirectReply)(nil), "bot.SendDirectReply")
	proto.RegisterType((*Activity)(nil), "bot.Activity")
	proto.RegisterType((*SaveProductResult)(nil), "bot.SaveProductResult")
	proto.RegisterType((*NotifyMessageRequest)(nil), "bot.NotifyMessageRequest")
	proto.RegisterType((*NotifyMessageResult)(nil), "bot.NotifyMessageResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for FetcherService service

type FetcherServiceClient interface {
	RetrieveActivities(ctx context.Context, in *RetrieveActivitiesRequest, opts ...grpc.CallOption) (*RetrieveActivitiesReply, error)
	SendDirect(ctx context.Context, in *SendDirectRequest, opts ...grpc.CallOption) (*SendDirectReply, error)
}

type fetcherServiceClient struct {
	cc *grpc.ClientConn
}

func NewFetcherServiceClient(cc *grpc.ClientConn) FetcherServiceClient {
	return &fetcherServiceClient{cc}
}

func (c *fetcherServiceClient) RetrieveActivities(ctx context.Context, in *RetrieveActivitiesRequest, opts ...grpc.CallOption) (*RetrieveActivitiesReply, error) {
	out := new(RetrieveActivitiesReply)
	err := grpc.Invoke(ctx, "/bot.FetcherService/RetrieveActivities", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fetcherServiceClient) SendDirect(ctx context.Context, in *SendDirectRequest, opts ...grpc.CallOption) (*SendDirectReply, error) {
	out := new(SendDirectReply)
	err := grpc.Invoke(ctx, "/bot.FetcherService/SendDirect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FetcherService service

type FetcherServiceServer interface {
	RetrieveActivities(context.Context, *RetrieveActivitiesRequest) (*RetrieveActivitiesReply, error)
	SendDirect(context.Context, *SendDirectRequest) (*SendDirectReply, error)
}

func RegisterFetcherServiceServer(s *grpc.Server, srv FetcherServiceServer) {
	s.RegisterService(&_FetcherService_serviceDesc, srv)
}

func _FetcherService_RetrieveActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetcherServiceServer).RetrieveActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bot.FetcherService/RetrieveActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetcherServiceServer).RetrieveActivities(ctx, req.(*RetrieveActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FetcherService_SendDirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDirectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetcherServiceServer).SendDirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bot.FetcherService/SendDirect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetcherServiceServer).SendDirect(ctx, req.(*SendDirectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FetcherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bot.FetcherService",
	HandlerType: (*FetcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveActivities",
			Handler:    _FetcherService_RetrieveActivities_Handler,
		},
		{
			MethodName: "SendDirect",
			Handler:    _FetcherService_SendDirect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for SaveTrendService service

type SaveTrendServiceClient interface {
	SaveProduct(ctx context.Context, in *Activity, opts ...grpc.CallOption) (*SaveProductResult, error)
}

type saveTrendServiceClient struct {
	cc *grpc.ClientConn
}

func NewSaveTrendServiceClient(cc *grpc.ClientConn) SaveTrendServiceClient {
	return &saveTrendServiceClient{cc}
}

func (c *saveTrendServiceClient) SaveProduct(ctx context.Context, in *Activity, opts ...grpc.CallOption) (*SaveProductResult, error) {
	out := new(SaveProductResult)
	err := grpc.Invoke(ctx, "/bot.SaveTrendService/SaveProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SaveTrendService service

type SaveTrendServiceServer interface {
	SaveProduct(context.Context, *Activity) (*SaveProductResult, error)
}

func RegisterSaveTrendServiceServer(s *grpc.Server, srv SaveTrendServiceServer) {
	s.RegisterService(&_SaveTrendService_serviceDesc, srv)
}

func _SaveTrendService_SaveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Activity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaveTrendServiceServer).SaveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bot.SaveTrendService/SaveProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaveTrendServiceServer).SaveProduct(ctx, req.(*Activity))
	}
	return interceptor(ctx, in, info, handler)
}

var _SaveTrendService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bot.SaveTrendService",
	HandlerType: (*SaveTrendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveProduct",
			Handler:    _SaveTrendService_SaveProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for TelegramService service

type TelegramServiceClient interface {
	NotifyMessage(ctx context.Context, in *NotifyMessageRequest, opts ...grpc.CallOption) (*NotifyMessageResult, error)
}

type telegramServiceClient struct {
	cc *grpc.ClientConn
}

func NewTelegramServiceClient(cc *grpc.ClientConn) TelegramServiceClient {
	return &telegramServiceClient{cc}
}

func (c *telegramServiceClient) NotifyMessage(ctx context.Context, in *NotifyMessageRequest, opts ...grpc.CallOption) (*NotifyMessageResult, error) {
	out := new(NotifyMessageResult)
	err := grpc.Invoke(ctx, "/bot.TelegramService/NotifyMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TelegramService service

type TelegramServiceServer interface {
	NotifyMessage(context.Context, *NotifyMessageRequest) (*NotifyMessageResult, error)
}

func RegisterTelegramServiceServer(s *grpc.Server, srv TelegramServiceServer) {
	s.RegisterService(&_TelegramService_serviceDesc, srv)
}

func _TelegramService_NotifyMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).NotifyMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bot.TelegramService/NotifyMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).NotifyMessage(ctx, req.(*NotifyMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TelegramService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bot.TelegramService",
	HandlerType: (*TelegramServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyMessage",
			Handler:    _TelegramService_NotifyMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("bot.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 575 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x6d, 0x9a, 0x36, 0xb1, 0x27, 0x69, 0xda, 0x2c, 0x81, 0x3a, 0xe1, 0x43, 0x60, 0x81, 0x94,
	0x0b, 0x3d, 0x04, 0x2e, 0x48, 0x1c, 0xa8, 0x54, 0x55, 0x80, 0x44, 0x85, 0xdc, 0xf4, 0xc0, 0x29,
	0x72, 0xed, 0x69, 0xb3, 0xc2, 0x1f, 0x61, 0xbd, 0x8e, 0xf0, 0x99, 0xbf, 0xc2, 0x4f, 0xe3, 0x87,
	0xb0, 0x3b, 0xbb, 0x6e, 0xd3, 0x26, 0xbd, 0xed, 0xcc, 0x9b, 0x79, 0x3b, 0xfb, 0xe6, 0xd9, 0xe0,
	0x5e, 0xe6, 0xf2, 0x68, 0x21, 0x72, 0x99, 0xb3, 0xa6, 0x3a, 0xfa, 0x7f, 0x1a, 0x30, 0x0c, 0x50,
	0x0a, 0x8e, 0x4b, 0x3c, 0x8e, 0x24, 0x5f, 0x72, 0xc9, 0xb1, 0x08, 0xf0, 0x57, 0x89, 0x85, 0x64,
	0xaf, 0xa0, 0x9b, 0x62, 0x26, 0x79, 0x9e, 0xcd, 0xb2, 0x30, 0x45, 0xaf, 0xf1, 0xb2, 0x31, 0x76,
	0x83, 0x8e, 0xcd, 0x9d, 0xa9, 0x14, 0x1b, 0x82, 0x13, 0x5e, 0x49, 0x14, 0x33, 0x1e, 0x7b, 0xdb,
	0x0a, 0x6e, 0x06, 0x6d, 0x8a, 0xbf, 0xc4, 0x8c, 0xc1, 0x8e, 0xac, 0x16, 0xe8, 0xed, 0x50, 0x17,
	0x9d, 0xd9, 0x00, 0x76, 0x13, 0x9e, 0x72, 0xe9, 0xed, 0x52, 0xad, 0x09, 0xfc, 0x13, 0xe8, 0x9f,
	0x63, 0x16, 0x9f, 0x70, 0x81, 0x91, 0xac, 0x2f, 0x7f, 0x0a, 0xae, 0x9c, 0x0b, 0x0c, 0x63, 0x4d,
	0x6d, 0x6e, 0x76, 0x4c, 0xc2, 0x72, 0xe3, 0x6f, 0x49, 0x57, 0x6a, 0x6e, 0x75, 0xf6, 0x3f, 0xc1,
	0xe1, 0xa6, 0xa7, 0x2c, 0x92, 0x8a, 0xbd, 0x81, 0x96, 0xc0, 0xa2, 0x4c, 0xa4, 0x22, 0x6a, 0x8e,
	0x3b, 0x93, 0xbd, 0x23, 0xad, 0x83, 0xad, 0xaa, 0x02, 0x0b, 0xfa, 0x7d, 0xd8, 0x5f, 0x9d, 0x43,
	0x75, 0xfa, 0xff, 0xb6, 0xc1, 0xa9, 0xeb, 0x58, 0x0f, 0xb6, 0xed, 0x2c, 0xcd, 0x40, 0x9d, 0x74,
	0xbc, 0xf8, 0x69, 0x67, 0x50, 0x27, 0x2d, 0x46, 0x8a, 0x31, 0x0f, 0xf5, 0xc4, 0x4d, 0xca, 0xb6,
	0x29, 0x56, 0x03, 0xab, 0xd7, 0x18, 0xa8, 0x14, 0x89, 0x55, 0xc4, 0xd4, 0x5e, 0x88, 0x84, 0x1d,
	0x42, 0xbb, 0x2c, 0x8c, 0x86, 0x46, 0x97, 0x96, 0x0e, 0x4d, 0x17, 0x01, 0xa4, 0x7e, 0xcb, 0x74,
	0xe9, 0x04, 0x49, 0xff, 0x1a, 0x7a, 0xa6, 0x2b, 0x0d, 0xaf, 0x91, 0x78, 0xdb, 0x54, 0xd1, 0xa5,
	0x66, 0x9d, 0xd4, 0xdc, 0x6f, 0x81, 0xd9, 0x7d, 0x61, 0x3c, 0xd3, 0x08, 0x71, 0x39, 0x54, 0xd9,
	0xbf, 0x41, 0x2e, 0x2c, 0x70, 0xb3, 0x34, 0x77, 0x65, 0x69, 0x1e, 0xb4, 0xa3, 0x3c, 0xd5, 0xb5,
	0x1e, 0x98, 0x57, 0xd9, 0x90, 0x3d, 0x07, 0x88, 0xd4, 0x46, 0xa4, 0xa2, 0x0e, 0xa5, 0xd7, 0xa1,
	0xd9, 0x5d, 0x9b, 0x39, 0x96, 0x6c, 0x0c, 0x07, 0x31, 0x69, 0x39, 0xbb, 0xdd, 0x64, 0x97, 0x18,
	0x7a, 0x26, 0x3f, 0xb5, 0xfb, 0xf4, 0x3f, 0x28, 0x07, 0x84, 0x4b, 0xfc, 0x2e, 0xf2, 0xb8, 0xd4,
	0xd2, 0xeb, 0x75, 0xac, 0xc9, 0xad, 0xcc, 0x23, 0xd4, 0x82, 0x2b, 0x52, 0xdc, 0x09, 0x4c, 0xe0,
	0x7f, 0x85, 0xc1, 0x59, 0x2e, 0xf9, 0x55, 0xf5, 0x0d, 0x8b, 0x42, 0x3d, 0xba, 0xf6, 0x8f, 0x9e,
	0x7a, 0x1e, 0x66, 0x19, 0x26, 0xd6, 0x3d, 0x75, 0xa8, 0x91, 0xd4, 0xd4, 0xda, 0xdd, 0xd5, 0xa1,
	0xff, 0x18, 0x1e, 0xdd, 0xe3, 0xd2, 0x83, 0x4c, 0xfe, 0x36, 0xa0, 0x77, 0x8a, 0x32, 0x9a, 0xa3,
	0x38, 0x47, 0xb1, 0xe4, 0x11, 0xb2, 0x29, 0xb0, 0x75, 0xb3, 0xb1, 0x17, 0xe4, 0xab, 0x07, 0x3f,
	0xa8, 0xd1, 0xb3, 0x07, 0x71, 0xed, 0xb5, 0x2d, 0xf6, 0x11, 0xe0, 0xd6, 0x80, 0xec, 0x09, 0x55,
	0xaf, 0x7d, 0x19, 0xa3, 0xc1, 0x5a, 0x9e, 0xba, 0x27, 0x9f, 0xe1, 0x40, 0x8b, 0x38, 0x15, 0x0a,
	0xa9, 0xe7, 0x7c, 0x0f, 0x9d, 0x15, 0x61, 0xd9, 0x5d, 0xe3, 0x8f, 0xec, 0x0d, 0xf7, 0x95, 0x9f,
	0xfc, 0x80, 0xfd, 0x29, 0x26, 0x78, 0x2d, 0xc2, 0xb4, 0x26, 0x3a, 0x85, 0xbd, 0x3b, 0xd2, 0xb0,
	0x21, 0xf5, 0x6e, 0x92, 0x7e, 0xe4, 0x6d, 0x82, 0xe8, 0x0b, 0xdb, 0xba, 0x6c, 0xd1, 0xdf, 0xe7,
	0xdd, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x34, 0xd7, 0x67, 0x8a, 0x04, 0x00, 0x00,
}
