port: 2010
host: 0.0.0.0
db:
    debug:    true
    user:     postgres
    password: 1234
    host:     db
    port:     5432
    base:     postgres

upload_service: http://images:8080
natsURL: "nats://nats:4222"
debug: true
