port: 2010
host: 0.0.0.0
debug: true
coreServer: core:3005
upload_service: http://mandible:8089

db:
    debug:    true
    user:     postgres
    password: 1234
    host:     db
    port:     5432
    base:     postgres

nats:
    url: nats://nats:4222
    stanCluster: stan
    stanID: chat1
