port: 2010
host: 0.0.0.0
debug: true
rpc:
    core: core:3005
    checker: checker:2013
upload_service: http://mandible:8089

db:
    debug:    true
    user:     postgres
    password: 1234
    host:     db
    port:     5432
    base:     postgres

nats:
    url: nats://nats:4222
    stanCluster: stan
    stanID: chat1
    
unanswered:
    - short:
        delay: 5s
    - long:
        delay: 3m
    - user:
        delay: 3m
        forUser: true
