Port: 8089
MaxFileSize: 20971520
HashLength: 7
UserAgent: "ImgurGo (https://github.com/gophergala/ImgurGo)"
Stores:
  - Type: "selectel"
    container: "pub"
    user: "54431"
    key: "cnH0eeqj"
    NamePathRegex: ""
    NamePathMap: "${ImageSize}/${ImageName}"
    rootPath: "/upload"

DatadogEnabled: false
DatadogHostname: "127.0.0.1"
