rpc: :7777
chatServer: "chat:2010"
coinsServer: "trendcoin:2014"

debug: true

http:
  listen: :7780
  public: "http://localhost:7780/callback"
  redirect: "http://localhost:3002/chat/%v/payed/%v"

db:
  debug:    true
  user:     postgres
  password: 1234
  host:     db
  port:     5432
  base:     postgres

nats:
  url: nats://nats:4222
  stanCluster: stan
  stanID: payment1

payture:
  key: "MerchantTrendeverp2p"
  url: "https://sandbox2.payture.com"

ewallet:
  sandbox: true
  secret: cococo
