rpc: :12326
# dummy | mts | atompark
sender: dummy

debug: true

db:
  debug:    true
  user:     postgres
  password: 1234
  host:     db
  port:     5432
  base:     postgres

atompark:
  test:        1
  keypublic:  de0b3db31f6f277d688b097c2e0f6a49
  keyprivate: e0bcb10cd2bbdb35596de9649feb5a4a
  sender:      Trendever

telegramChannel: new_sms

nats:
  url: nats://nats:4222
  stanCluster: stan
  stanID: sms1
