// Code generated by protoc-gen-go.
// source: checker.proto
// DO NOT EDIT!

/*
Package checker is a generated protocol buffer package.

It is generated from these files:
	checker.proto

It has these top-level messages:
	CheckRequest
	CheckReply
*/
package checker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckRequest struct {
	Ids []uint64 `protobuf:"varint,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *CheckRequest) Reset()                    { *m = CheckRequest{} }
func (m *CheckRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()               {}
func (*CheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CheckReply struct {
}

func (m *CheckReply) Reset()                    { *m = CheckReply{} }
func (m *CheckReply) String() string            { return proto.CompactTextString(m) }
func (*CheckReply) ProtoMessage()               {}
func (*CheckReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*CheckRequest)(nil), "checker.CheckRequest")
	proto.RegisterType((*CheckReply)(nil), "checker.CheckReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for CheckerService service

type CheckerServiceClient interface {
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckReply, error)
}

type checkerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCheckerServiceClient(cc *grpc.ClientConn) CheckerServiceClient {
	return &checkerServiceClient{cc}
}

func (c *checkerServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckReply, error) {
	out := new(CheckReply)
	err := grpc.Invoke(ctx, "/checker.CheckerService/Check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CheckerService service

type CheckerServiceServer interface {
	Check(context.Context, *CheckRequest) (*CheckReply, error)
}

func RegisterCheckerServiceServer(s *grpc.Server, srv CheckerServiceServer) {
	s.RegisterService(&_CheckerService_serviceDesc, srv)
}

func _CheckerService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/checker.CheckerService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CheckerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "checker.CheckerService",
	HandlerType: (*CheckerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _CheckerService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("checker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0x48, 0x4d,
	0xce, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x14, 0xb8,
	0x78, 0x9c, 0x41, 0xcc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x01, 0x2e, 0xe6, 0xcc,
	0x94, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x96, 0x20, 0x10, 0x53, 0x89, 0x87, 0x8b, 0x0b, 0xaa,
	0xa2, 0x20, 0xa7, 0xd2, 0xc8, 0x9d, 0x8b, 0xcf, 0x19, 0xa2, 0x35, 0x38, 0xb5, 0xa8, 0x2c, 0x33,
	0x39, 0x55, 0xc8, 0x94, 0x8b, 0x15, 0x2c, 0x22, 0x24, 0xaa, 0x07, 0xb3, 0x03, 0xd9, 0x44, 0x29,
	0x61, 0x74, 0x61, 0xa0, 0x31, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x87, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xb8, 0xd4, 0x20, 0xb0, 0x99, 0x00, 0x00, 0x00,
}
