// Code generated by protoc-gen-go.
// source: payment.proto
// DO NOT EDIT!

/*
Package payment is a generated protocol buffer package.

It is generated from these files:
	payment.proto

It has these top-level messages:
	CreateOrderRequest
	CreateOrderReply
	BuyOrderRequest
	BuyOrderReply
	CancelOrderRequest
	CancelOrderReply
	ChatMessageNewOrder
	ChatMessagePaymentFinished
	ChatMessageOrderCancelled
*/
package payment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Currency int32

const (
	Currency_RUB Currency = 0
	Currency_USD Currency = 1
	Currency_COP Currency = 2
)

var Currency_name = map[int32]string{
	0: "RUB",
	1: "USD",
	2: "COP",
}
var Currency_value = map[string]int32{
	"RUB": 0,
	"USD": 1,
	"COP": 2,
}

func (x Currency) String() string {
	return proto.EnumName(Currency_name, int32(x))
}
func (Currency) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Errors int32

const (
	Errors_OK Errors = 0
	// internal errors
	Errors_INVALID_DATA       Errors = 1
	Errors_DB_FAILED          Errors = 2
	Errors_ALREADY_PAYED      Errors = 3
	Errors_PAY_CANCELLED      Errors = 4
	Errors_ANOTHER_OPEN_ORDER Errors = 5
	// external errors
	Errors_INIT_FAILED Errors = 127
	Errors_PAY_FAILED  Errors = 128
	Errors_CHAT_DOWN   Errors = 129
)

var Errors_name = map[int32]string{
	0:   "OK",
	1:   "INVALID_DATA",
	2:   "DB_FAILED",
	3:   "ALREADY_PAYED",
	4:   "PAY_CANCELLED",
	5:   "ANOTHER_OPEN_ORDER",
	127: "INIT_FAILED",
	128: "PAY_FAILED",
	129: "CHAT_DOWN",
}
var Errors_value = map[string]int32{
	"OK":                 0,
	"INVALID_DATA":       1,
	"DB_FAILED":          2,
	"ALREADY_PAYED":      3,
	"PAY_CANCELLED":      4,
	"ANOTHER_OPEN_ORDER": 5,
	"INIT_FAILED":        127,
	"PAY_FAILED":         128,
	"CHAT_DOWN":          129,
}

func (x Errors) String() string {
	return proto.EnumName(Errors_name, int32(x))
}
func (Errors) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Direction int32

const (
	Direction_CLIENT_PAYS Direction = 0
	Direction_CLIENT_RECV Direction = 1
)

var Direction_name = map[int32]string{
	0: "CLIENT_PAYS",
	1: "CLIENT_RECV",
}
var Direction_value = map[string]int32{
	"CLIENT_PAYS": 0,
	"CLIENT_RECV": 1,
}

func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}
func (Direction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CreateOrderRequest struct {
	Amount         uint64    `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	Currency       Currency  `protobuf:"varint,2,opt,name=currency,enum=payment.Currency" json:"currency,omitempty"`
	LeadId         uint64    `protobuf:"varint,3,opt,name=lead_id,json=leadId" json:"lead_id,omitempty"`
	UserId         uint64    `protobuf:"varint,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ConversationId uint64    `protobuf:"varint,5,opt,name=conversation_id,json=conversationId" json:"conversation_id,omitempty"`
	Direction      Direction `protobuf:"varint,6,opt,name=direction,enum=payment.Direction" json:"direction,omitempty"`
	ShopCardNumber string    `protobuf:"bytes,7,opt,name=shop_card_number,json=shopCardNumber" json:"shop_card_number,omitempty"`
}

func (m *CreateOrderRequest) Reset()                    { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()               {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateOrderReply struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Error        Errors `protobuf:"varint,2,opt,name=error,enum=payment.Errors" json:"error,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (m *CreateOrderReply) Reset()                    { *m = CreateOrderReply{} }
func (m *CreateOrderReply) String() string            { return proto.CompactTextString(m) }
func (*CreateOrderReply) ProtoMessage()               {}
func (*CreateOrderReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type BuyOrderRequest struct {
	PayId uint64 `protobuf:"varint,1,opt,name=pay_id,json=payId" json:"pay_id,omitempty"`
	Ip    string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	// parameters to check permissions
	LeadId    uint64    `protobuf:"varint,3,opt,name=lead_id,json=leadId" json:"lead_id,omitempty"`
	Direction Direction `protobuf:"varint,4,opt,name=direction,enum=payment.Direction" json:"direction,omitempty"`
}

func (m *BuyOrderRequest) Reset()                    { *m = BuyOrderRequest{} }
func (m *BuyOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*BuyOrderRequest) ProtoMessage()               {}
func (*BuyOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type BuyOrderReply struct {
	RedirectUrl  string `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl" json:"redirect_url,omitempty"`
	Error        Errors `protobuf:"varint,2,opt,name=error,enum=payment.Errors" json:"error,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (m *BuyOrderReply) Reset()                    { *m = BuyOrderReply{} }
func (m *BuyOrderReply) String() string            { return proto.CompactTextString(m) }
func (*BuyOrderReply) ProtoMessage()               {}
func (*BuyOrderReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CancelOrderRequest struct {
	PayId uint64 `protobuf:"varint,1,opt,name=pay_id,json=payId" json:"pay_id,omitempty"`
	// parameters to check permissions
	LeadId    uint64    `protobuf:"varint,3,opt,name=lead_id,json=leadId" json:"lead_id,omitempty"`
	Direction Direction `protobuf:"varint,4,opt,name=direction,enum=payment.Direction" json:"direction,omitempty"`
}

func (m *CancelOrderRequest) Reset()                    { *m = CancelOrderRequest{} }
func (m *CancelOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*CancelOrderRequest) ProtoMessage()               {}
func (*CancelOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type CancelOrderReply struct {
	Cancelled    bool   `protobuf:"varint,1,opt,name=cancelled" json:"cancelled,omitempty"`
	Error        Errors `protobuf:"varint,2,opt,name=error,enum=payment.Errors" json:"error,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (m *CancelOrderReply) Reset()                    { *m = CancelOrderReply{} }
func (m *CancelOrderReply) String() string            { return proto.CompactTextString(m) }
func (*CancelOrderReply) ProtoMessage()               {}
func (*CancelOrderReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// chat messages
type ChatMessageNewOrder struct {
	PayId    uint64   `protobuf:"varint,1,opt,name=pay_id,json=payId" json:"pay_id,omitempty"`
	Amount   uint64   `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Currency Currency `protobuf:"varint,3,opt,name=currency,enum=payment.Currency" json:"currency,omitempty"`
}

func (m *ChatMessageNewOrder) Reset()                    { *m = ChatMessageNewOrder{} }
func (m *ChatMessageNewOrder) String() string            { return proto.CompactTextString(m) }
func (*ChatMessageNewOrder) ProtoMessage()               {}
func (*ChatMessageNewOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ChatMessagePaymentFinished struct {
	PayId     uint64    `protobuf:"varint,1,opt,name=pay_id,json=payId" json:"pay_id,omitempty"`
	Success   bool      `protobuf:"varint,3,opt,name=success" json:"success,omitempty"`
	Amount    uint64    `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
	Currency  Currency  `protobuf:"varint,5,opt,name=currency,enum=payment.Currency" json:"currency,omitempty"`
	Direction Direction `protobuf:"varint,6,opt,name=direction,enum=payment.Direction" json:"direction,omitempty"`
}

func (m *ChatMessagePaymentFinished) Reset()                    { *m = ChatMessagePaymentFinished{} }
func (m *ChatMessagePaymentFinished) String() string            { return proto.CompactTextString(m) }
func (*ChatMessagePaymentFinished) ProtoMessage()               {}
func (*ChatMessagePaymentFinished) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ChatMessageOrderCancelled struct {
	PayId uint64 `protobuf:"varint,1,opt,name=pay_id,json=payId" json:"pay_id,omitempty"`
}

func (m *ChatMessageOrderCancelled) Reset()                    { *m = ChatMessageOrderCancelled{} }
func (m *ChatMessageOrderCancelled) String() string            { return proto.CompactTextString(m) }
func (*ChatMessageOrderCancelled) ProtoMessage()               {}
func (*ChatMessageOrderCancelled) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "payment.CreateOrderRequest")
	proto.RegisterType((*CreateOrderReply)(nil), "payment.CreateOrderReply")
	proto.RegisterType((*BuyOrderRequest)(nil), "payment.BuyOrderRequest")
	proto.RegisterType((*BuyOrderReply)(nil), "payment.BuyOrderReply")
	proto.RegisterType((*CancelOrderRequest)(nil), "payment.CancelOrderRequest")
	proto.RegisterType((*CancelOrderReply)(nil), "payment.CancelOrderReply")
	proto.RegisterType((*ChatMessageNewOrder)(nil), "payment.ChatMessageNewOrder")
	proto.RegisterType((*ChatMessagePaymentFinished)(nil), "payment.ChatMessagePaymentFinished")
	proto.RegisterType((*ChatMessageOrderCancelled)(nil), "payment.ChatMessageOrderCancelled")
	proto.RegisterEnum("payment.Currency", Currency_name, Currency_value)
	proto.RegisterEnum("payment.Errors", Errors_name, Errors_value)
	proto.RegisterEnum("payment.Direction", Direction_name, Direction_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for PaymentService service

type PaymentServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error)
	BuyOrder(ctx context.Context, in *BuyOrderRequest, opts ...grpc.CallOption) (*BuyOrderReply, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderReply, error)
}

type paymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaymentServiceClient(cc *grpc.ClientConn) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error) {
	out := new(CreateOrderReply)
	err := grpc.Invoke(ctx, "/payment.PaymentService/CreateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) BuyOrder(ctx context.Context, in *BuyOrderRequest, opts ...grpc.CallOption) (*BuyOrderReply, error) {
	out := new(BuyOrderReply)
	err := grpc.Invoke(ctx, "/payment.PaymentService/BuyOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderReply, error) {
	out := new(CancelOrderReply)
	err := grpc.Invoke(ctx, "/payment.PaymentService/CancelOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PaymentService service

type PaymentServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error)
	BuyOrder(context.Context, *BuyOrderRequest) (*BuyOrderReply, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderReply, error)
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_BuyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).BuyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/BuyOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).BuyOrder(ctx, req.(*BuyOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _PaymentService_CreateOrder_Handler,
		},
		{
			MethodName: "BuyOrder",
			Handler:    _PaymentService_BuyOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _PaymentService_CancelOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0xc6, 0xf9, 0xf7, 0x40, 0x12, 0xb3, 0x47, 0x87, 0x63, 0x38, 0xe7, 0xe2, 0xd4, 0x15, 0x2a,
	0x42, 0x02, 0x55, 0xf4, 0xbe, 0x92, 0xb1, 0x4d, 0xb1, 0x9a, 0xda, 0xd1, 0x12, 0xa8, 0xb8, 0xb2,
	0x8c, 0xb3, 0x2a, 0x91, 0x12, 0x3b, 0x5d, 0xdb, 0x54, 0x91, 0xaa, 0xfe, 0xa8, 0x6f, 0xd0, 0x37,
	0xe8, 0xcb, 0xf4, 0x41, 0xfa, 0x24, 0xdd, 0xf5, 0x3f, 0x3f, 0x11, 0x54, 0xe2, 0x6e, 0xe7, 0x9b,
	0xd9, 0x9d, 0x6f, 0xbe, 0xf1, 0x8c, 0xa1, 0x3b, 0x77, 0x17, 0x33, 0xe2, 0x47, 0xfb, 0x73, 0x1a,
	0x44, 0x01, 0x6a, 0x67, 0xa6, 0xf2, 0xbd, 0x06, 0x48, 0xa3, 0xc4, 0x8d, 0x88, 0x4d, 0xc7, 0x84,
	0x62, 0xf2, 0x3e, 0x26, 0x61, 0x84, 0x36, 0xa0, 0xe5, 0xce, 0x82, 0xd8, 0x8f, 0x64, 0xe1, 0x7f,
	0x61, 0xa7, 0x81, 0x33, 0x0b, 0xed, 0x41, 0xc7, 0x8b, 0x29, 0x25, 0xbe, 0xb7, 0x90, 0x6b, 0xcc,
	0xd3, 0x3b, 0x58, 0xdf, 0xcf, 0x5f, 0xd6, 0x32, 0x07, 0x2e, 0x42, 0xd0, 0x3f, 0xd0, 0x9e, 0x12,
	0x77, 0xec, 0x4c, 0xc6, 0x72, 0x3d, 0x7d, 0x87, 0x9b, 0xe6, 0x98, 0x3b, 0xe2, 0x90, 0x50, 0xee,
	0x68, 0xa4, 0x0e, 0x6e, 0x32, 0xc7, 0x33, 0xe8, 0x7b, 0x81, 0x7f, 0x45, 0x68, 0xe8, 0x46, 0x93,
	0xc0, 0xe7, 0x01, 0xcd, 0x24, 0xa0, 0x57, 0x85, 0x59, 0xe0, 0x73, 0x10, 0xc7, 0x13, 0x4a, 0x3c,
	0x6e, 0xca, 0xad, 0x84, 0x0a, 0x2a, 0xa8, 0xe8, 0xb9, 0x07, 0x97, 0x41, 0x68, 0x07, 0xa4, 0xf0,
	0x32, 0x98, 0x3b, 0x9e, 0x4b, 0xc7, 0x8e, 0x1f, 0xcf, 0x2e, 0x08, 0x95, 0xdb, 0xec, 0xa2, 0x88,
	0x7b, 0x1c, 0xd7, 0x18, 0x6c, 0x25, 0xa8, 0xe2, 0x83, 0x74, 0x4d, 0x93, 0xf9, 0x74, 0x81, 0x7a,
	0x50, 0x63, 0x5c, 0x52, 0x35, 0xd8, 0x09, 0x6d, 0x43, 0x93, 0x50, 0x1a, 0xd0, 0x4c, 0x86, 0x7e,
	0x91, 0xdb, 0xe0, 0x68, 0x88, 0x53, 0x2f, 0x7a, 0x0a, 0xdd, 0xe4, 0xe0, 0xcc, 0x48, 0x18, 0xba,
	0xef, 0x48, 0xa2, 0x83, 0x88, 0xd7, 0x12, 0xf0, 0x4d, 0x8a, 0x29, 0xdf, 0x04, 0xe8, 0x1f, 0xc6,
	0x8b, 0x6b, 0x1d, 0xf8, 0x1b, 0x5a, 0xec, 0x45, 0xa7, 0xc8, 0xd9, 0x64, 0x16, 0x2b, 0x9b, 0xd3,
	0x98, 0x27, 0x39, 0x45, 0x46, 0x63, 0xbe, 0x5c, 0xe1, 0x6b, 0xfa, 0x34, 0x1e, 0xa0, 0x8f, 0xf2,
	0x09, 0xba, 0x25, 0x09, 0x5e, 0xf2, 0x13, 0x58, 0xa3, 0x24, 0xf5, 0x3b, 0x31, 0x9d, 0x26, 0x44,
	0x44, 0xbc, 0x9a, 0x63, 0xa7, 0x74, 0xfa, 0xa8, 0x2a, 0x5c, 0xb1, 0x2f, 0xd1, 0xf5, 0x3d, 0x32,
	0x7d, 0x88, 0x0e, 0x8f, 0x58, 0xf7, 0x47, 0xd6, 0xed, 0x6a, 0x5e, 0x5e, 0xfa, 0x7f, 0x20, 0x7a,
	0x09, 0x36, 0x25, 0x69, 0xe2, 0x0e, 0x2e, 0x81, 0x47, 0xad, 0x3a, 0x84, 0xbf, 0xb4, 0x4b, 0x37,
	0xca, 0x4c, 0x8b, 0x7c, 0x48, 0x58, 0x2c, 0x2b, 0xbb, 0x9c, 0xcb, 0xda, 0xd2, 0xb9, 0xac, 0xdf,
	0x3b, 0x97, 0xca, 0x4f, 0x01, 0xb6, 0x2a, 0x59, 0x87, 0x69, 0xe4, 0xd1, 0xc4, 0x9f, 0x84, 0x97,
	0xac, 0xbe, 0x25, 0xc9, 0x65, 0x68, 0x87, 0xb1, 0xe7, 0xb1, 0x3b, 0x49, 0x8e, 0x0e, 0xce, 0xcd,
	0x0a, 0xad, 0xc6, 0x52, 0x5a, 0xcd, 0xfb, 0xd7, 0xc5, 0x1f, 0xcf, 0xb4, 0x72, 0x00, 0x9b, 0x95,
	0x3a, 0x12, 0xe9, 0xb4, 0xa2, 0x4d, 0x77, 0x97, 0xb1, 0xbb, 0x0d, 0x9d, 0x3c, 0x37, 0x6a, 0x43,
	0x1d, 0x9f, 0x1e, 0x4a, 0x2b, 0xfc, 0x70, 0x7a, 0xa2, 0x4b, 0x02, 0x3f, 0x68, 0xf6, 0x50, 0xaa,
	0xed, 0xfe, 0x10, 0xa0, 0x95, 0xf6, 0x13, 0xb5, 0xa0, 0x66, 0xbf, 0x66, 0x41, 0x12, 0xac, 0x99,
	0xd6, 0x99, 0x3a, 0x30, 0x75, 0x47, 0x57, 0x47, 0x2a, 0x8b, 0xee, 0x82, 0xa8, 0x1f, 0x3a, 0x47,
	0xaa, 0x39, 0x30, 0x74, 0xa9, 0x86, 0xd6, 0xa1, 0xab, 0x0e, 0xb0, 0xa1, 0xea, 0xe7, 0xce, 0x50,
	0x3d, 0x67, 0x50, 0x9d, 0x43, 0xec, 0xe8, 0x68, 0xaa, 0xa5, 0x19, 0x03, 0x1e, 0xd5, 0x60, 0x6a,
	0x21, 0xd5, 0xb2, 0x47, 0xc7, 0x06, 0x76, 0xec, 0xa1, 0x61, 0x39, 0x36, 0xd6, 0x0d, 0x2c, 0x35,
	0x51, 0x1f, 0x56, 0x4d, 0xcb, 0x1c, 0xe5, 0xcf, 0x7d, 0x66, 0x00, 0xf0, 0xbb, 0x99, 0xfd, 0x45,
	0x60, 0xd3, 0x2f, 0x6a, 0xc7, 0xea, 0xc8, 0xd1, 0xed, 0xb7, 0x96, 0xf4, 0x55, 0xd8, 0xdd, 0x63,
	0xe9, 0x8b, 0xfd, 0xc6, 0xae, 0x6b, 0x03, 0xd3, 0xb0, 0x46, 0x3c, 0xf7, 0x09, 0xa3, 0x5b, 0x02,
	0xd8, 0xd0, 0xce, 0x24, 0xe1, 0xe0, 0x97, 0x00, 0xbd, 0xac, 0xd7, 0x27, 0x84, 0x5e, 0x4d, 0x3c,
	0x82, 0x5e, 0xb1, 0x98, 0x72, 0xd5, 0xa1, 0x7f, 0xcb, 0xf6, 0xdc, 0xfa, 0x29, 0x6c, 0x6d, 0xde,
	0xed, 0x64, 0xf3, 0xa2, 0xac, 0xa0, 0x97, 0xd0, 0xc9, 0xb7, 0x07, 0x92, 0x8b, 0xc0, 0x1b, 0x5b,
	0x6d, 0x6b, 0xe3, 0x0e, 0x4f, 0x7a, 0x9f, 0x13, 0x29, 0xa7, 0xb0, 0x4a, 0xe4, 0xd6, 0x4e, 0xa8,
	0x12, 0xb9, 0x31, 0xb8, 0xca, 0xca, 0x45, 0x2b, 0xf9, 0xc3, 0xbd, 0xf8, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x98, 0xbc, 0x0c, 0x16, 0xf2, 0x06, 0x00, 0x00,
}
